dong.spring.ai.joyai.chat.base-url=http://api.chatrhino.jd.com/api
dong.spring.ai.joyai.chat.api-key=RS22yv1LDPNTqsNTDIP6Wq0rxrdS4s88
dong.spring.ai.joyai.chat.options.model=Chatrhino-81B-Pro
dong.spring.ai.joyai.chat.completions-path=/v2/chat/completions

dong.spring.ai.joyai.model2.chat.base-url=http://api.chatrhino.jd.com/api
dong.spring.ai.joyai.model2.chat.api-key=RS22yv1LDPNTqsNTDIP6Wq0rxrdS4s88
dong.spring.ai.joyai.model2.chat.options.model=Chatrhino-750B
dong.spring.ai.joyai.model2.chat.completions-path=/v2/chat/completions

dong.spring.ai.joyai.model3.chat.base-url=http://api.chatrhino.jd.com/api
dong.spring.ai.joyai.model3.chat.api-key=RS22yv1LDPNTqsNTDIP6Wq0rxrdS4s88
dong.spring.ai.joyai.model3.chat.options.model=Chatrhino-10B
dong.spring.ai.joyai.model3.chat.completions-path=/v2/chat/completions

dong.spring.ai.joyai.embedding.base-url=http://inferential-api-service-apipre.omniforce.svc.lf06.n.jd.local
dong.spring.ai.joyai.embedding.api-key=RS22yv1LDPNTqsNTDIP6Wq0rxrdS4s88
dong.spring.ai.joyai.embedding.options.model=bge-m3

dong.spring.ai.mcp.client.jsf.config[0].interface-name=com.jd.framework.console.domain.DongBootService
dong.spring.ai.mcp.client.jsf.config[0].app-name=dong-boot-initializr
dong.spring.ai.vectorstore.vearch.enabled=true
dong.spring.ai.vectorstore.vearch.host=http://dong-boot.vearch.jd.local
dong.spring.ai.vectorstore.vearch.username=root
dong.spring.ai.vectorstore.vearch.password=NMCU00PXIC47QTXL
dong.spring.ai.memory.jdbc.enabled=false
dong.spring.ai.memory.jimdb.enabled=true
dong.spring.ai.memory.jimdb.cluster=jim1

dong.spring.ai.joysafety.enabled=true
dong.spring.ai.joysafety.access-key=JDR_dong-boot-initializr
dong.spring.ai.joysafety.access-token=27d08240-2c45-4209-819c-70072dbb5443
dong.spring.ai.joysafety.options.business-type=toe
