# TODO You need to replace configurations with your own settings,sql connection configurations in DalConfiguration class
dong.dal.dp1.ds-name=${DONG_DAL_NAME}
dong.dal.dp1.version=${DONG_DAL_VERSION}
