# JSF: TODO You need to replace configurations with your own settings
dong.jsf.enableAutoPublish=true
dong.jsf.demo.alias=${JSF_ALIAS}
dong.jsf.servers.server1.threads=300
dong.jsf.servers.server1.port=22001
