# TODO You need to replace configurations with your own settings
dong.sso.enabled=false
sso.clientId=${SSO_KEY}
sso.activeEnvironment=${SSO_ENV}
sso.clientSecret=${SSO_TOKEN}
sso.endpoint=https://ssa.jdtest.net/sso/login
sso.loginUrl=https://ssa.jdtest.net/sso/login

sso.excludePath=/static,/js,/css,/images,/favicon.ico
sso.apiEndpoint=https://ssa.jdtest.net

sso.cookieDomainName=jd.com
sso.jdqEnable=false
sso.loadJsf=false
