## IMPORTANT!!!
## Please read HELP.md to see how to configure and start the project.

# spring.application.name : TODO You need to replace application name with your own project name
spring.application.name=dong-boot-initializr

# Spring Web
server.port=8080






