## Please use the continuous delivery platform to manage application static configuration
## joyspace: https://joyspace.jd.com/pages/riJTieWIWE0njWLliSuz
DONG_DAL_NAME=dongboot-dal-demo
DONG_DAL_VERSION=v1
DUCC_URI1=jdos_dong-boot-initializr/dongboot/config/test?longPolling=60000&necessary=true
JIM1_NAME=dongboottest
JSF_ALIAS=annotation-test
SSO_KEY=test3
SSO_TOKEN=347c6161e79f4b6a8873202dd5fe7e8f
SSO_ENV=test
